### PR TITLE
Add: bench option

### PR DESCRIPTION
**Pull request by RaulTrombin**
Allow users to compile and deploy the binary for benchmarking tests. From: [issue 31](https://github.com/houseabsolute/actions-rust-cross/issues/31)

Use:

```
 - name: Cross-compile benchmark
        uses: RaulTrombin/actions-rust-cross@add_bench
        with:
          command: bench
          target: ${{ matrix.TARGET }}
          args: "--no-run"
```

image

### CODE REVIEW

**Comment by autarch** [comment]
Hi, thanks for your PR! I'm pretty finicky about my projects (see [this blog post](https://blog.urth.org/2022/07/02/what-s-the-right-way-to-merge-a-pull-request/) for details), so I rarely merge a PR as-is. I can move forward on your PR in one of two ways:

1. I check it out locally, fiddle with it as needed, merge it locally, and simply close this PR. This will preserve at least one commit with your name on it, but the PR will show up as closed in your GitHub stats.
2. If you enable me to push directly to your fork, I can do my fiddling, then force push to your fork and merge the resulting PR. Again, this will preserve at least one commit with your name on it, but you _also_ get credit for the PR merge in your GitHub stats. The only downside is that I will be force pushing directly to your fork.

Please let me know which approach you'd prefer. If I don't hear from you before I get around to working on this PR I'll go with option 1.

Thanks again for your contribution!

**Comment by autarch** [comment]
I just pushed directly to the PR branch. I didn't need access to your forked project. This is the default for PRs, though you can disable it.

**Comment by RaulTrombin** [comment]
> I just pushed directly to the PR branch. I didn't need access to your forked project. This is the default for PRs, though you can disable it.

I was able to run with rust stable if use criterion, https://github.com/houseabsolute/actions-rust-cross/commit/6362a683db66fcee318a7ee94e34ad3a450c6a44

but still have the same issue for these 3 targets with faillure:
freeBSB, netBSB and aarch64-windows.

They build but can't execute, with arg='no-run' all targets are [Ok](https://github.com/RaulTrombin/actions-rust-cross/actions/runs/11990316714/job/33427687886).

**Comment by RaulTrombin** [comment]
oh, or add on test.yaml:
 `if: ${{ matrix.platform.can_test }}` for bench test.

**Pull request merged**
