### PR TITLE
Update action.yml to add a context to support monorepos

### PR DESCRIPTION
**Pull request by aaronvg**
add context field to set working directory

### CODE REVIEW

**Comment by larsnaesbye** [comment]
Seconded. I'd use this in our monorepo if it supported it :-)

**Comment by aaronvg** [comment]
I published my action, if it helps you can use it

**Comment by autarch** [comment]
Thanks for this PR! This looks like a very useful feature. I'll try to take a look at this over the coming weekend.

**Comment by autarch** [comment]
Hi, thanks for your PR! I'm pretty finicky about my projects (see [this blog post](https://blog.urth.org/2022/07/02/what-s-the-right-way-to-merge-a-pull-request/) for details), so I rarely merge a PR as-is. I can move forward on your PR in one of two ways:

1. I check it out locally, fiddle with it as needed, merge it locally, and simply close this PR. This will preserve at least one commit with your name on it, but the PR will show up as closed in your GitHub stats.
2. If you enable me to push directly to your fork, I can do my fiddling, then force push to your fork and merge the resulting PR. Again, this will preserve at least one commit with your name on it, but you _also_ get credit for the PR merge in your GitHub stats. The only downside is that I will be force pushing directly to your fork.

Please let me know which approach you'd prefer. If I don't hear from you before I get around to working on this PR I'll go with option #1.

Thanks again for your contribution!

**Comment by aaronvg** [comment]
I actually dont care if my name is on it or not. Feel free to check it out or make the same changes and commit

**Comment by autarch** [comment]
I ended up merging this from the CLI. Thanks!

**Pull request closed without merging**
